bahare zorufchi/Models/kala.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bahare_zorufchi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kala
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kala()
        {
            this.comments = new HashSet<comment>();
        }
    
        public long ID { get; set; }
        public int categoryID { get; set; }
        public string Name { get; set; }
        public string Producer { get; set; }
        public string Description { get; set; }
        public string ImageURL { get; set; }
        public int Original_Price { get; set; }
        public int Discount_Price { get; set; }
        public bool IsAvailable { get; set; }
        public Nullable<int> like { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
    }
}

bahare zorufchi/Controllers/CommentController.cs
using bahare_zorufchi.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace bahare_zorufchi.Controllers
{
    public class CommentController : Controller
    {

        okalaDBEntities db = new okalaDBEntities();

        

        public ActionResult Accept(int id)
        {
            comment commentToChange = db.comments.Find(id);
            commentToChange.IsAccepted = true;

            db.Entry(commentToChange).State = EntityState.Modified;

            db.SaveChanges();

            return RedirectToAction("Details", "kala", new { id = commentToChange.kalaID });
        }

       

        public ActionResult Reject(int id)
        {
            comment commentToChange = db.comments.Find(id);
            commentToChange.IsAccepted = false;

            db.Entry(commentToChange).State = EntityState.Modified;

            db.SaveChanges();

            return RedirectToAction("Details", "News", new { id = commentToChange.kalaID });

        }

        

        public ActionResult Accept1(int id)
        {
            comment commentToChange = db.comments.Find(id);
            commentToChange.IsAccepted = true;

            db.Entry(commentToChange).State = EntityState.Modified;

            db.SaveChanges();

            return RedirectToAction("CommentManagement");
        }

      

        public ActionResult Reject1(int id)
        {
            comment commentToChange = db.comments.Find(id);
            commentToChange.IsAccepted = false;

            db.Entry(commentToChange).State = EntityState.Modified;

            db.SaveChanges();

            return RedirectToAction("CommentManagement");

        }


        
        public ActionResult CommentManagement()
        {
            var commentList = db.comments.OrderByDescending(p => p.ID);
            return View(commentList);
        }



        // GET: Comment
        public ActionResult Index()
        {
            return View();
        }

        // GET: Comment/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Comment/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Comment/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Comment/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Comment/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

       

        // GET: Comment/Delete/5
        public ActionResult Delete(int id)
        {
            comment cmt = db.comments.Find(id);
            if (cmt == null)
            {
                return HttpNotFound();
            }
            return View(cmt);
        }





        
        // POST: Comment/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
           comment cmt = db.comments.Find(id);
            db.comments.Remove(cmt);
            db.SaveChanges();
            return RedirectToAction("CommentManagement");
        }













    }
}

bahare zorufchi/Controllers/kalaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using bahare_zorufchi.Models;
using System.IO;
using System.Data.Entity;


namespace bahare_zorufchi.Controllers
{
    public class kalaController : Controller
    {
        okalaDBEntities db = new okalaDBEntities();
        // GET: kala
        public ActionResult Index(int id = 1)
        {
            okalaDBEntities db = new okalaDBEntities();
            int take = 4;
            int skip = (id - 1) * take;
            int count = db.kalas.Count();
            ViewBag.PageID = id;
            ViewBag.pagecount = Convert.ToInt32(Math.Ceiling(count /(double) take));
           var list= db.kalas.OrderByDescending(p => p.ID).Skip(skip).Take(take).ToList();
            return View(list);
        }

        // GET: kala/Details/5
        public ActionResult Details(int id)
        {  
          kala kala = db.kalas.Find(id);
            if (kala == null) 
            {
                return HttpNotFound();
            }
           
            return View(kala);
        }
        //kala.= kala.visitors + 1;
        //    db.Entry(kala).State = EntityState.Modified;
        //    db.SaveChanges();

        // GET: kala/Create
        public ActionResult Create()
        {
            return View();
        }
     
        //public ActionResult Details(int id, comment cmt)
        //{
        //    cmt.kalaID = id;

        //    db.comments.Add(cmt);
        //    db.SaveChanges();

        //    return View(db.kalas.Find(id));
        //}

        [HttpPost]
        public ActionResult Details(int id, comment cmt)
        {
            cmt.kalaID = id;

            db.comments.Add(cmt);
            db.SaveChanges();

            return View("partialcomments",cmt);
        }

        // POST: kala/Create
        [HttpPost]
        public ActionResult Create(kala kalaitem,HttpPostedFileBase picture)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid == true) {

                    if (picture != null && picture.ContentLength > 0)
                    {
                        var filename = picture.FileName;
                        var masireFile = Path.Combine(Server.MapPath("~/Content/Image/"), filename);
                        picture.SaveAs(masireFile);

                        kalaitem.ImageURL = "~/Content/Image/" + filename;
                    }
                    db.kalas.Add(kalaitem);
                db.SaveChanges();
                return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: kala/Edit/5
        public ActionResult Edit(int id)
        {
            kala kala = db.kalas.Find(id);
            if (kala == null) 
            {
                return HttpNotFound();
            }

            return View(kala);
        }

        // POST: kala/Edit/5

        [HttpPost]
        public ActionResult Edit(int id,kala editeditem ,HttpPostedFileBase picture)
        {
            if(ModelState.IsValid)
            {
                if (picture != null && picture.ContentLength > 0)
                {
                    var filename = picture.FileName;
                    var masireFile = Path.Combine(Server.MapPath("~/Content/Image/"), filename);
                    picture.SaveAs(masireFile);

                    editeditem.ImageURL = "~/Content/Image/" + filename;
                }

                db.Entry(editeditem).State = EntityState.Modified;
                db.SaveChanges();
                return  RedirectToAction("Index");
            }
            return View(editeditem);

      
        }

        // GET: kala/Delete/5
        public ActionResult Delete(int id)
        {
            kala kala = db.kalas.Find(id);
            if(kala==null)
            {
                return HttpNotFound();
            }
            return View(kala);
        }

        // POST: kala/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection kalaitem)
        {
            kala kala = db.kalas.Find(id);
            db.kalas.Remove(kala);
            db.SaveChanges();
            return RedirectToAction("index");
       
        }
        public ActionResult search()
        { 
            return View();
        }

        [HttpPost]
        public ActionResult search(string TxtsearchedTitle, string TxtsearchedText)
        {
            var res = db.kalas.Where(a => a.Name.Contains(TxtsearchedTitle) && a.Description.Contains(TxtsearchedText));
            List<kala> searchedkala = res.ToList();
            return View("result", searchedkala);
        }



        [HttpPost]
        public ActionResult search2(string TxtsearchedTitle, string TxtsearchedText)
        {
            var res = db.kalas.Where(a => a.Name.Contains(TxtsearchedTitle) && a.Description.Contains(TxtsearchedText));
            List<kala> searchedkala = res.ToList();
            return View("Partialresult", searchedkala);
        }













        public ActionResult Addlike(int id)
        {
            kala kala = db.kalas.Find(id);
            if (kala == null)
            {
                return HttpNotFound();
            }
            kala.like = kala.like + 1;
            db.Entry(kala).State = EntityState.Modified;
            db.SaveChanges();

            return View("Details", kala);
        }
























        //[HttpPost]
        //public ActionResult search2(string TxtsearchedTitle, string TxtsearchedText)
        //{
        //    var res = db.kalas.Where(a => a.Name.Contains(TxtsearchedTitle) && a.Text.contains(TxtsearchedTitle));
        //    List<kala>searchedkala =res.ToList();
        //    return View("Partialresult" , searchkalas);
        //}
    }
}

bahare zorufchi/Views/kala/Create.cshtml
@model bahare_zorufchi.Models.kala

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/myprojectlayoutstyles.cshtml";
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
}

<h2>ایجاد کالا جدید</h2>


@using (Html.BeginForm("create", "kala", FormMethod.Post, new { id = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.categoryID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.categoryID, new[]{
               new SelectListItem{Text="انواع کرم",Value="1"},new SelectListItem{Text="انواع آب رسان",Value="2"},
               new SelectListItem{Text="انواع رژلب",Value="3"},
                 new SelectListItem{Text="انواع کیف ارایشی",Value="4"},  new SelectListItem{Text="انواه شوینده پوست",Value="5"},
               new SelectListItem{Text="انواع ماسک مو",Value="6"},
                   new SelectListItem{Text="انواع براش",Value="7"} }, "یک گزینه را انتخاب کنید")


                @Html.ValidationMessageFor(model => model.categoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Producer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Producer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Producer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Avatar" name="Picture" />
                @Html.ValidationMessageFor(model => model.ImageURL, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Original_Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Original_Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Original_Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Discount_Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Discount_Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Discount_Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    در انبار موجود
                    @Html.RadioButtonFor(b => b.IsAvailable, "true", new { @checked = "checked" })هست
                    @Html.RadioButtonFor(b => b.IsAvailable, "false")نیست
                    @Html.ValidationMessageFor(model => model.IsAvailable, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ثبت اطلاعات" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

bahare zorufchi/Views/kala/Delete.cshtml
@model bahare_zorufchi.Models.kala

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/myprojectlayoutstyles.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>kala</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.categoryID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Producer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Producer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageURL)
        </dt>

        <dd>
            <div class="axkala"> <img src="@Url.Content(Model.ImageURL)"></div>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Original_Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Original_Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Discount_Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Discount_Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="حذف کالا" class="btn btn-default" /> |
            @Html.ActionLink("بازگشت به صفحه اصلی", "Index")
        </div>
    }
</div>

bahare zorufchi/Views/kala/Details.cshtml
@model bahare_zorufchi.Models.kala

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/myprojectlayoutstyles.cshtml";
}
@section scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
}

<h2 style="text-align:center;">جزییات کالا</h2>
@using (Html.BeginForm("Addlike", "kala", new {id=Model.ID}))
            {
                <input type="submit" value="❤️" style="border:1px solid"/>
            }
<div>@Html.DisplayFor(model => model.like)</div>
<div>
    
    <hr />
    <dl class="dl-horizontal" >
        <dd>
            <div style="width:300px; height:300px" class="axkala"> <img style="width:100%; height:100%" src="@Url.Content(Model.ImageURL)"></div>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.categoryID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.category.Name)
            @Model.category.Name


        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)


        </dt>

        <dd>
            @* @Html.DisplayFor(model => model.Name)*@
            
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Producer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Producer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>



        <dt>
            @Html.DisplayNameFor(model => model.Original_Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Original_Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Discount_Price)
            @Html.Label("گروه خبر")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Discount_Price)
            @*@Model.category.Name;*@
        </dd>






        
            @*@Html.DisplayNameFor(model => model.IsAvailable)*@
            @if (Model.IsAvailable == true)
            {
                <div style="background-color:forestgreen;width:100px;height:40px;text-align:center; ">موجود هست</div>
            }
            else
            {
                <div style="background-color:crimson;width:100px;height:40px;text-align:center;">موجود نیست</div>
            }


        

        <dd>
            @*@Html.DisplayFor(model => model.IsAvailable)*@
        </dd>

    </dl>
</div>

<br><br><br>

@*<div id="AddComment">
        @using (Html.BeginForm()) {

            <div>
                <label>نام:</label>
                <input type="text" name="Name" /><!--  hatman bayad vijegi name dashte bashand ta be samte server ersal shavand -->
            </div>
            <div>
                <label>ایمیل:</label>
                <input type="text" name="Email" /><!--  hatman bayad vijegi name dashte bashand ta be samte server ersal shavand -->
            </div>
            <div>
                <label>نظر شما : </label>
                <textarea cols="30" rows="10" name="Text"></textarea><!--  hatman bayad vijegi name dashte bashand ta be samte server ersal shavand -->
            </div>
            <div>
               <input type="submit" value="ثبت نظر" />
            </div>
        }
    </div>*@


<div>
    @using (Ajax.BeginForm("Details", "Kala", new AjaxOptions { UpdateTargetId = "divcommentlist", InsertionMode = InsertionMode.Replace }))
    {
        <div>
            <label>نام</label>
            <input type="text" name="Name" />
        </div>
        <div>
            <label>ایمیل</label>
            <input type="text" name="Email" />
        </div>
        <div>
            <label>متن</label>
            <textarea cols="30" rows="10" name="Text"></textarea>
        </div>
        <div>
            <input type="submit" value="ثبت نظر" />
        </div>
    }
</div>
<h3>لیست کامنت ها</h3>

<div id="divcommentlist">

    
        @foreach (var CommentItem in Model.comments.OrderByDescending(p => p.ID))
        {
            <div>
                @CommentItem.Name : @CommentItem.Text

                @if (CommentItem.IsAccepted == false)
                {
                    @Html.ActionLink("تأیید ", "Accept", "Comment", new { id = CommentItem.ID }, null)
                }
                else
                {
                    <a href="/Comment/Reject/@CommentItem.ID">رد</a>
                }
            </div>
        }
   

    
        @*@foreach (var CommentItem in Model.comments.Where(z => z.IsAccepted == true).OrderByDescending(p => p.ID))
        {
            <div> @CommentItem.Name : @CommentItem.Text </div>
        }*@
    






</div>


<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

bahare zorufchi/Views/kala/Edit.cshtml
@model bahare_zorufchi.Models.kala

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/myprojectlayoutstyles.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "kala", FormMethod.Post, new {id="form",enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>kala</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)



    <div class="form-group">
        @Html.LabelFor(model => model.categoryID, htmlAttributes: new { @class = "control-label col-md-2" })

        <div class="col-md-10">
            @Html.DropDownListFor(x => x.categoryID, new[]{
           new SelectListItem{Text="انواع کرم",Value="1"},new SelectListItem{Text="انواع آب رسان",Value="2"},
           new SelectListItem{Text="انواع رژلب",Value="3"},
             new SelectListItem{Text="انواع کیف ارایشی",Value="4"},  new SelectListItem{Text="انواه شوینده پوست",Value="5"},
           new SelectListItem{Text="انواع ماسک مو",Value="6"},
               new SelectListItem{Text="انواع براش",Value="7"} }, "یک گزینه را انتخاب کنید")


            @Html.ValidationMessageFor(model => model.categoryID, "", new { @class = "text-danger" })


        </div>

    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Producer, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Producer, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Producer, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ImageURL, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.HiddenFor(model => model.ImageURL, new { htmlAttributes = new { @class = "form-control" } })
            <img src="@Url.Content(Model.ImageURL)" style="width:200px;height:170px;">
            <input type="file" id="Avatar" name="picture"/>

            @Html.ValidationMessageFor(model => model.ImageURL, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Original_Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Original_Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Original_Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Discount_Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Discount_Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Discount_Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IsAvailable, "در انبار موجود", htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.RadioButtonFor(b => b.IsAvailable, "true", new { @checked = "checked" })هست
        @Html.RadioButtonFor(b => b.IsAvailable, "false")نیست
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.IsAvailable)
                @Html.ValidationMessageFor(model => model.IsAvailable, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="ویرایش" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

bahare zorufchi/Views/kala/Partialcomments.cshtml
@model bahare_zorufchi.Models.comment

<div>
    <h4>comment</h4>
    @Html.DisplayFor(Model => Model.Name):
    @Html.DisplayFor(Model => Model.Text)
</div>

bahare zorufchi/Views/kala/Partialresult.cshtml
@model IEnumerable<bahare_zorufchi.Models.kala>





@if (Model.Count() != 0)
{
   

        <div>

            @foreach (var item in Model)
            {
                <div style="width: 240px; height: 340px;background-color:aqua;border-radius:40px;border:solid black;background-color:white;float:right; ">
                    <div style="width: 220px; height: 185px;margin-right:10px;margin-bottom:25px;"> <img style="border-radius: 30px;" src="@Url.Content(item.ImageURL)"></div>
                    <div style="text-align:center"><a href="./kala/details/@item.ID">@item.Name</a></div>
                    <div style="text-align:center"> <p>@item.Description</p></div>
                    <del><div style="text-align: center; color: red;">@item.Original_Price</div></del>
                    <div style="text-align:center;"> <a>@item.Discount_Price</a></div>




                </div>
            }
        </div>

   
}



else
{
    <p>هیچ موردی پیدا نشد</p>
}

bahare zorufchi/Views/kala/search.cshtml
@{
    ViewBag.Title = "search";
    Layout = "~/Views/Shared/myprojectlayoutstyles.cshtml";
}


@section scripts{

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
}

@using (Html.BeginForm())
{
    <h2>search</h2>
    <p>جستجو کالایی که دارای عبارت زیر در عنوان خبر هستند.</p>
    @Html.TextBox("TxtsearchedTitle")
    <p>عبارات زیر در متن کالا هستند.</p>
    @Html.TextBox("TxtsearchedText")
    <input type="submit" value="نمایش صفحات جستجو در صفحه بعد" />

}



<hr />



<p>نتایج جستجو را در همین صفحه نمایش بدهد</p>
@using (Ajax.BeginForm("search2", "kala", new AjaxOptions { UpdateTargetId = "divresult", InsertionMode = InsertionMode.Replace }))
{
    <h2>search</h2>
    <p>جستجو کالایی که دارای عبارت زیر در عنوان خبر هستند</p>
    @Html.TextBox("TxtsearchedTitle")
    <p>عبارات زیر در متن کالا هستند.</p>
    @Html.TextBox("TxtsearchedText")
    <input type="submit" value="نمایش صفحات جستجو در همین صفحه" />

}
<div id="divresult">

</div>